import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import landingImg from "@/public/landingPageHugo.png"
import landingLogo from "@/public/landingPageLogo.png"
import Button from '@/components/Button'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.main_container}>
          <div className={styles.pageImg}>
            <Image className={styles.landingImg} src={landingImg} width="300" />
          </div>
          <div className={styles.pageContent}>
          <div className={styles.logoBx}>
            <Image src={landingLogo} width='200' />
            <p className={styles.tagline}>No Worries. We Stand By You.</p>
          </div>
          <div className={styles.action}>
            <div className={styles.memberIcon}>
              <Image />
            </div>
            <Link href='/introduction'>
                {/* <button className={styles.actionBtn}>Get Started</button> */}
                <Button text="Get Started" color='#896686' width='180'/>
            </Link>
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
